services:
  - type: web
    name: equipmanage-frontend
    env: node
    plan: free
    region: ohio
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_TELEMETRY_DISABLED
        value: '1'
      - key: NEXT_PUBLIC_ENV
        value: production
